# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mike.W" #"Hello. I'm Mike Woodcock."
email: 'MikeWoodcockC@gmail.com'
description: "" #"I'm a software developer from Chicago creating useful things for the web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://notanymike.github.io/site" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 'NotAnyMike'
github_username: 'NotAnyMike'
medium_username: '' #'blog.jamigibbs.com'
cv_url: 'https://drive.google.com/file/d/1QZWhXaDQVXVAy36f7ov2EnawCoKF_y-B/view'
section_title: 'All'
section_subtitle: "Here is a list of most of the things I have written/done/thought, enjoy."
projects_title: 'Latest Work'
projects_subtitle: "Here is a list of some of my lastest works or projects, enjoy."
unrelated_title: 'General stuff'
unrelated_subtitle: "Some projects resulting of having free time or different hobbies, enjoy."

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 100
footer_text: ' Powered by Jekyll with Phantom template by Jami Gibbs © Copyright Mike Woodcock.'
admin_name: 'Mike.W'
google_analytics: "UA-77835108-1" # Update with your own tracking ID
enable_contact: false
permalink: /:title/

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'All' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/stuff', text: 'Other stuff' }
  - { url: '/about', text: 'About me' }
  - { url: '/list100', text: 'List 100' }
